services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    container_name: 'rag-from-pdf-container'
    environment:
      - 'POSTGRES_DB=mydb'
      - 'POSTGRES_PASSWORD=mypassword'
      - 'POSTGRES_USER=myuser'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5433:5432'
